### PR TITLE
fix typo in FULL_DISTRO_NAME token

### PR DESCRIPTION
**Pull request by dolphinoracle**
just missing a "%" on the end of the token.

### CODE REVIEW

**Comment by BitJam** [comment]
Thanks!  Those will all be changing to %=NAME=% very soon.  This will allow me to do better error checking (but it wouldn't catch this error).

**Comment by dolphinoracle** [comment]
Snapshot uses the existing tokens

**Comment by dolphinoracle** [comment]
Never mind different template for snapshot anyway

**Comment by BitJam** [comment]
We are safe in two ways.  First the %NAME% strings still get substituted as before.  Second, these only throw errors if --strict is used.  So there is no change for older templates.  If you want the new error-checking feature then you need to use the new %=NAME=% format (and use --strict).  You are free to use both formats in the same file.

**Pull request merged**
